### ISSUE TITLE
Objeto 3d en Web

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-promastergamer#1]

**Comment by FedericoVictorianoSierra** [comment]
[Actividad 5 Web.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-realidad-aumentada-en-sitio-web-promastergamer/files/14921027/Actividad.5.Web.pdf)

**Comment by NoeliaGlez** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
